CREATE VIEW DISCIPLINAS_PROFESSOR AS(
SELECT 	  P.NOME AS PROFESSOR
		, P.FORMACAO
		, D.COD_DISCIPLINA
		, D.NOME_DISCIPLINA
		, D.CARGA_HORARIA
FROM OFERTAS O
INNER JOIN 	PROFESSORES P ON
			O.MATRICULA = P.MATRICULA
INNER JOIN 	DISCIPLINAS D ON 
			O.COD_DISCIPLINA = D.COD_DISCIPLINA
);

CREATE VIEW ALUNOS_MATRICULADOS AS (
	SELECT 	A.MATRICULA
			, A.NOME AS ALUNO
			, AO.SEMESTRE
			, O.HORARIO_INICIAL
			, O.HORARIO_FINAL
			, O.DIA_SEMANA
			, P.NOME AS PROFESSOR
			, D.NOME_DISCIPLINA
FROM ALUNOS_OFERTAS AO
INNER JOIN ALUNOS A ON 
	AO.MATRICULA = A.MATRICULA
INNER JOIN OFERTAS O ON 
	AO.COD_OFERTA = O.COD_OFERTA
INNER JOIN PROFESSORES P ON 
	O.MATRICULA = P.MATRICULA
INNER JOIN DISCIPLINAS D ON 
	O.COD_DISCIPLINA = D.COD_DISCIPLINA
)