DROP TABLE ALUNOS;
DROP TABLE TELEFONES;
DROP TABLE PROFESSORES;
DROP TABLE DISCIPLINAS;
DROP TABLE OFERTAS;
DROP TABLE ALUNOS_OFERTAS;

CREATE TABLE ALUNOS(
	MATRICULA NUMERIC NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL
);

CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA NUMERIC NOT NULL
);

CREATE TABLE PROFESSORES(
	MATRICULA NUMERIC(5) NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL
);

CREATE TABLE DISCIPLINAS(
	COD_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	COD_DISCIPLINA_DEPENDENCIA NUMERIC
);

CREATE TABLE OFERTAS(
	COD_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR(20) NOT NULL,
	MATRICULA NUMERIC(5) NOT NULL,
	COD_DISCIPLINA NUMERIC NOT NULL
);

CREATE TABLE ALUNOS_OFERTAS(
	MATRICULA NUMERIC NOT NULL,
	COD_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL
);
