-- ADD
ALTER TABLE ALUNOS ADD EMAIL VARCHAR2(200);
ALTER TABLE ALUNOS ADD CPF VARCHAR2(11);

ALTER TABLE PROFESSORES ADD CONTATO VARCHAR2(200);

ALTER TABLE OFERTAS ADD DATA_CRIACAO DATE;

-- MODIFY
ALTER TABLE ALUNOS MODIFY EMAIL VARCHAR2(250);

ALTER TABLE OFERTAS MODIFY DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL ;

-- RENAME COLUMN
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME TO NOME_ALUNO;

ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
ALTER TABLE PROFESSORES RENAME COLUMN NOME TO NOME_PROFESSOR;

ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;

ALTER TABLE ALUNOS_OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;

ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
