CREATE TABLE ALUNOS(
	MATRICULA NUMERIC NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	DATA_NASCIMENTO DATE NOT NULL,
	
	CONSTRAINT PK_MATRICULA PRIMARY KEY(MATRICULA)
);

CREATE TABLE TELEFONES(
	TELEFONE VARCHAR2(11) NOT NULL,
	MATRICULA NUMERIC NOT NULL,
	
	CONSTRAINT PK_TELEFONE PRIMARY KEY (TELEFONE),
	CONSTRAINT FK_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES ALUNOS(MATRICULA)
);

CREATE TABLE PROFESSORES(
	MATRICULA NUMERIC(5) NOT NULL,
	NOME VARCHAR2(100) NOT NULL,
	FORMACAO VARCHAR2(100) NOT NULL,
	
	CONSTRAINT PK_MAT_PROFESSOR PRIMARY KEY(MATRICULA)
);

CREATE TABLE DISCIPLINAS(
	COD_DISCIPLINA NUMERIC NOT NULL,
	NOME_DISCIPLINA VARCHAR2(100) NOT NULL,
	CARGA_HORARIA NUMERIC(3) NOT NULL,
	EMENTA VARCHAR2(4000) NOT NULL,
	COD_DISCIPLINA_DEPENDENCIA NUMERIC,
	
	CONSTRAINT PK_COD_DISCIPLINA PRIMARY KEY(COD_DISCIPLINA),
	CONSTRAINT FK_COD_DISCIPLINA_DEPENDENTE FOREIGN KEY(COD_DISCIPLINA_DEPENDENCIA)
	REFERENCES DISCIPLINAS (COD_DISCIPLINA)
);

CREATE TABLE OFERTAS(
	COD_OFERTA NUMERIC NOT NULL,
	HORARIO_INICIAL TIMESTAMP NOT NULL,
	HORARIO_FINAL TIMESTAMP NOT NULL,
	DIA_SEMANA VARCHAR(20) NOT NULL,
	MATRICULA NUMERIC(5) NOT NULL,
	COD_DISCIPLINA NUMERIC NOT NULL,
	
	CONSTRAINT PK_COD_OFERTA PRIMARY KEY  (COD_OFERTA),
	CONSTRAINT FK_MAT_PROFESSOR FOREIGN KEY (MATRICULA) REFERENCES PROFESSORES(MATRICULA),
	CONSTRAINT FK_COD_DISCIPLINA FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINAS(COD_DISCIPLINA)
);

CREATE TABLE ALUNOS_OFERTAS(
	MATRICULA NUMERIC NOT NULL,
	COD_OFERTA NUMERIC NOT NULL,
	LIMITE_ALUNOS NUMERIC NOT NULL,
	SEMESTRE VARCHAR2(6) NOT NULL,
	DATA_INICIAL DATE NOT NULL,
	DATA_FINAL DATE NOT NULL,
	
	CONSTRAINT PK_ALUNOS_OFERTAS PRIMARY KEY (MATRICULA, COD_OFERTA),
	CONSTRAINT FK_AO_MATRICULA FOREIGN KEY (MATRICULA) REFERENCES ALUNOS(MATRICULA),
	CONSTRAINT FK_AO_COD_OFERTA FOREIGN KEY (COD_OFERTA) REFERENCES OFERTAS(COD_OFERTA)
);
