-- ADD
ALTER TABLE ALUNOS ADD EMAIL VARCHAR2(200);
ALTER TABLE ALUNOS ADD CPF VARCHAR2(11);
ALTER TABLE PROFESSORES ADD CONTATO VARCHAR2(200);
ALTER TABLE OFERTAS ADD DATA_CRIACAO DATE;

-- MODIFY
ALTER TABLE ALUNOS MODIFY EMAIL VARCHAR2(250);
ALTER TABLE OFERTAS MODIFY DATA_CRIACAO DATE DEFAULT SYSDATE NOT NULL ;

-- RENAME COLUMN
ALTER TABLE ALUNOS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE ALUNOS RENAME COLUMN NOME TO NOME_ALUNO;
ALTER TABLE PROFESSORES RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;
ALTER TABLE PROFESSORES RENAME COLUMN NOME TO NOME_PROFESSOR;
ALTER TABLE DISCIPLINAS RENAME COLUMN EMENTA TO EMENTA_DISCIPLINA;
ALTER TABLE ALUNOS_OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_ALUNO;
ALTER TABLE OFERTAS RENAME COLUMN MATRICULA TO MATRICULA_PROFESSOR;

-- RENAME TABLE
ALTER TABLE TELEFONES RENAME TO TELEFONES_ALUNOS;
ALTER TABLE

-- DROP COLUMN
ALTER TABLE PROFESSORES DROP COLUMN CONTATO;
ALTER TABLE ALUNOS DROP COLUMN EMAIL;
ALTER TABLE ALUNOS DROP COLUMN CPF;


-- ADD PRIMARY KEY
ALTER TABLE TELEFONES_ALUNOS ADD PRIMARY KEY (TELEFONE);
ALTER TABLE ALUNOS ADD PRIMARY KEY (MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD PRIMARY KEY (MATRICULA_ALUNO, COD_OFERTA);
ALTER TABLE OFERTAS ADD PRIMARY KEY (COD_OFERTA);
ALTER TABLE PROFESSORES ADD PRIMARY KEY (MATRICULA_PROFESSOR);
ALTER TABLE DISCIPLINAS ADD PRIMARY KEY (COD_DISCIPLINA);

-- ADD CONSTRAINT
ALTER TABLE TELEFONES_ALUNOS ADD CONSTRAINT TELEFONE_ALUNO_FK FOREIGN KEY (MATRICULA) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD CONSTRAINT ALUNOS_ALUNO_FK FOREIGN KEY (MATRICULA_ALUNO) REFERENCES ALUNOS (MATRICULA_ALUNO);
ALTER TABLE ALUNOS_OFERTAS ADD CONSTRAINT ALUNOS_OFERTA_FK FOREIGN KEY (COD_OFERTA) REFERENCES OFERTAS (COD_OFERTA);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_PROFESSOR_FK FOREIGN KEY (MATRICULA_PROFESSOR) REFERENCES PROFESSORES (MATRICULA_PROFESSOR);
ALTER TABLE OFERTAS ADD CONSTRAINT OFERTAS_DISCIPLINAS_FK FOREIGN KEY (COD_DISCIPLINA) REFERENCES DISCIPLINAS (COD_DISCIPLINA);
ALTER TABLE DISCIPLINAS ADD CONSTRAINT DISCIPLINAS_DEPENDENCIA_FK FOREIGN KEY (COD_DISCIPLINA_DEPENDENCIA) REFERENCES DISCIPLINAS (COD_DISCIPLINA);